### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by white-gecko** [moehrenzahn/DevotionaliumPebble#1]
How can I install this Pebble App I could not find it in the rebble store:
https://apps.rebble.io/en_US/search/watchapps/1?dev_settings=true&native=false&query=Devotionalium

**Comment by moehrenzahn** [comment]
Hi Natanael,

thanks for your feedback. I had totally forgotten this project. 🤪

Because Pebble the company does no longer exist and their app store has been taken offline, this app is no longer available.

You can however attempt to sideload the `app.js` manually. I have no guarantee that this would work. I also haven't tested this app in a very long time. Let me know how it goes!
